site_name: Phonopy Spectroscopy
site_url: https://lucydot.github.io/phonopy_spectroscopy

theme:
  name: material
  locale: en

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [lib]
        options:
          heading_level: 2
- mkdocs-jupyter

nav:
- "Home": index.md
- "Installation": installation.md
- "Tutorials": 
    - "overview": ./tutorials/overview.md
    - "benzene": ./tutorials/benzene_derivatives_tutorial.md
    - "SiO2": ./tutorials/SiO2_tutorial.md
    - "test notebooks": ./tutorials/test_tutorial.ipynb
- "Reference": 
    - "Modules":
      - "phonon": ./reference/phonon.md
      - "structure": ./reference/structure.md
- "Background": background.md 
- "Development": development.md 
- "Credit": credit.md
